apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: demucs-worker:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: "6Gi"
          limits:
            memory: "8Gi"
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: "minio"
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_ACCESS_KEY
          value: "rootuser"
        - name: MINIO_SECRET_KEY
          value: "rootpass123"
